server:
  port: 8086
spring:
  application:
    name: sms-service

  rabbitmq:
    host: yun
    username: ugo
    password: ugo
    virtual-host: /ugo

ly:
  sms:
    accessKeyId: qqAIQ3u9clgBEgqz # 你自己的accessKeyId
    accessKeySecret: cch9t0C7MinrUz730Ju3Ub3PX3JSKU # 你自己的AccessKeySecret
    signName: qq商城 # 签名名称
    verifyCodeTemplate: SMS_1630573cc # 模板名称
