server:
  port: 8083
  #tomcat:
    #max-http-post-size: 20971520x
spring:
  applicatio n:
    name: search-service
  http:
    multipart:

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: yun:9300
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值

  rabbitmq:
    host: yun
    username: ugo
    password: ugo
    virtual-host: /ugo

eureka:
  client:
    service-url:
      defaultZone: http://yun:8761/eureka,http://yun:8762/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
ribbon:
  ConnectTimeout: 600000 # 连接超时时间(ms)
  ReadTimeout: 600000 # 通信超时时间(ms)
